apiVersion: v2
name: hami
description: A Helm chart for hami
type: application
version: 1.0.1
# renovate: helm=hami registry=https://project-hami.github.io/HAMi
appVersion: 2.10.0
annotations:
  otterscale.io/type: module
  module.otterscale.io/namespace: kube-system
  module.otterscale.io/depends-on: gpu-operator,prometheus-stack
dependencies:
  - name: hami
    version: 2.10.0
    repository: https://project-hami.github.io/HAMi
    condition: hami.enabled
