apiVersion: v2
name: kube-resource-orchestrator
description: A Helm chart for kro
type: application
version: 1.0.0
# renovate: helm=kro registry=oci://registry.k8s.io/kro/charts
appVersion: "0.9.3"
annotations:
  module.otterscale.io/namespace: "kro-system"
dependencies:
  - name: kro
    version: 0.9.3
    repository: oci://registry.k8s.io/kro/charts
    condition: kro.enabled
