{{- if .Values.featureWriter.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otterscale-nfd.fullname" . }}-feature-writer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale-nfd.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
