kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otterscale-llmisvc-config-reader
  namespace: otterscale-system
rules:
  - apiGroups: ["serving.kserve.io"]
    resources:
      - llminferenceserviceconfigs
      - llminferenceserviceconfigs/status
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otterscale-llmisvc-config-reader
  namespace: otterscale-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: otterscale-llmisvc-config-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: otterscale-kserve-admin
rules:
  - apiGroups:
      - serving.kserve.io
    resources:
      - llminferenceserviceconfigs
      - llminferenceservices
    verbs:
      - "*"
  - apiGroups:
      - serving.kserve.io
    resources:
      - llminferenceserviceconfigs/status
      - llminferenceservices/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: otterscale-kserve-edit
rules:
  - apiGroups:
      - serving.kserve.io
    resources:
      - llminferenceserviceconfigs
      - llminferenceservices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - serving.kserve.io
    resources:
      - llminferenceserviceconfigs/status
      - llminferenceservices/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: otterscale-kserve-view
rules:
  - apiGroups:
      - serving.kserve.io
    resources:
      - llminferenceserviceconfigs
      - llminferenceservices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - serving.kserve.io
    resources:
      - llminferenceserviceconfigs/status
      - llminferenceservices/status
    verbs:
      - get
