apiVersion: v2
name: leader-worker-set
description: A Helm chart for leader-worker-set
type: application
version: 1.0.0
# renovate: helm=lws registry=oci://registry.k8s.io/lws/charts
appVersion: "0.10.0"
annotations:
  otterscale.io/type: module
  module.otterscale.io/namespace: "lws-system"
dependencies:
  - name: lws
    version: "0.10.0"
    repository: "oci://registry.k8s.io/lws/charts"
    condition: lws.enabled
