apiVersion: v2
name: kubevirt
description: A Helm chart for kubevirt
type: application
version: 1.1.0
# renovate: image=quay.io/kubevirt/virt-operator
appVersion: v1.9.0
annotations:
  otterscale.io/type: module
  module.otterscale.io/namespace: kubevirt
