apiVersion: v2
name: otterscale-agent
description: A Helm chart for otterscale-agent
type: application
version: 1.0.0
# renovate: image=ghcr.io/otterscale/otterscale
appVersion: "v1.5.0-rc.1"
annotations:
  otterscale.io/type: module
  module.otterscale.io/namespace: "otterscale-system"
dependencies:
  - name: cert-manager
    # renovate: helm=cert-manager registry=oci://quay.io/jetstack/charts
    version: "1.21.1"
    repository: "oci://quay.io/jetstack/charts"
    condition: cert-manager.enabled
  - name: flux-operator
    # renovate: helm=flux-operator registry=oci://ghcr.io/controlplaneio-fluxcd/charts
    version: "0.58.1"
    repository: "oci://ghcr.io/controlplaneio-fluxcd/charts"
    condition: flux-operator.enabled
  - name: topolvm
    # renovate: helm=topolvm registry=https://topolvm.github.io/topolvm
    version: "17.1.0"
    repository: "https://topolvm.github.io/topolvm"
    condition: topolvm.enabled
