image:
  repository: ghcr.io/otterscale/otterscale
  tag: ""
  pullPolicy: IfNotPresent

agent:
  serverURL: "https://otterscale.example.com/api/"
  tunnelServerURL: "https://10.0.0.1:30300"
  cluster: "devel"

harbor:
  url: https://harbor.example.com

  robot:
    name: "robot$devel"
    secret: ""

clusterAdmin:
  enabled: true
  users: []

rbac:
  nodeReader:
    enabled: true

  storageClassReader:
    enabled: true

tenantOperator:
  enabled: true
  rancherProjectID: ""

licenseOperator:
  enabled: false

cert-manager:
  enabled: true

flux-operator:
  enabled: true

topolvm:
  enabled: false

flux:
  enabled: true

  instance:
    distribution:
      version: "2.9.x"
      registry: "ghcr.io/fluxcd"
    components:
      - source-controller
      - helm-controller
    cluster:
      type: kubernetes
      size: medium
      multitenant: true
      tenantDefaultServiceAccount: "view"
      networkPolicy: true
      domain: "cluster.local"
