apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "otterscale-agent.fullname" . }}
  labels:
    {{- include "otterscale-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "otterscale-agent.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "otterscale-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- if and .Values.clusterAdmin.enabled .Values.clusterAdmin.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "otterscale-agent.fullname" . }}-cluster-admin
  labels:
    {{- include "otterscale-agent.labels" . | nindent 4 }}
subjects:
  {{- range .Values.clusterAdmin.users }}
  - kind: User
    name: {{ . | quote }}
    apiGroup: rbac.authorization.k8s.io
  {{- end }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
