apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otterscale-agent.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale-agent.labels" . | nindent 4 }}
data:
  OTTERSCALE_AGENT_SERVER_URL: {{ .Values.agent.serverURL | quote }}
  OTTERSCALE_AGENT_TUNNEL_SERVER_URL: {{ .Values.agent.tunnelServerURL | quote }}
  OTTERSCALE_AGENT_CLUSTER: {{ .Values.agent.cluster | quote }}
  OTTERSCALE_AGENT_PROXY_PROMETHEUS_URL: {{ .Values.metrics.prometheusURL | quote }}
  OTTERSCALE_AGENT_PROXY_PROMETHEUS_CA_SECRET: {{ printf "%s/%s" .Values.metrics.caSecret.namespace .Values.metrics.caSecret.name | quote }}
{{- if .Values.clusterInfo.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otterscale-info
  namespace: kube-public
  labels:
    {{- include "otterscale-agent.labels" . | nindent 4 }}
data:
  externalAddress: {{ .Values.clusterInfo.externalAddress | quote }}
  nodePortRange: {{ .Values.clusterInfo.nodePortRange | quote }}
  {{- with .Values.clusterInfo.inferenceURL }}
  inferenceURL: {{ . | trimSuffix "/" | quote }}
  {{- end }}
{{- end }}
