{{- $trustedCA := .Values.trustedCA.secretName }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otterscale-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale-agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "otterscale-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otterscale-agent.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "otterscale-agent.fullname" . }}
      containers:
        - name: otterscale
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - agent
          env:
            - name: OTTERSCALE_AGENT_JOIN_TOKEN_FILE
              value: {{ printf "%s/token" (include "otterscale-agent.join.dir" .) | quote }}
            {{- if $trustedCA }}
            - name: SSL_CERT_DIR
              value: {{ include "otterscale-agent.trustedCA.dir" . | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "otterscale-agent.fullname" . }}-config
          volumeMounts:
            - name: join
              mountPath: {{ include "otterscale-agent.join.dir" . | quote }}
              readOnly: true
            {{- if $trustedCA }}
            - name: trusted-ca
              mountPath: {{ include "otterscale-agent.trustedCA.dir" . | quote }}
              readOnly: true
            {{- end }}
      volumes:
        - name: join
          secret:
            secretName: {{ include "otterscale-agent.join.secretName" . | quote }}
            items:
              - key: {{ include "otterscale-agent.join.secretKey" . | quote }}
                path: token
        {{- if $trustedCA }}
        - name: trusted-ca
          secret:
            secretName: {{ $trustedCA | quote }}
            items:
              - key: {{ .Values.trustedCA.key | quote }}
                path: {{ .Values.trustedCA.key | quote }}
        {{- end }}
