apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otterscale-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale-agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "otterscale-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otterscale-agent.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "otterscale-agent.fullname" . }}
      containers:
        - name: otterscale
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - agent
          envFrom:
            - configMapRef:
                name: {{ include "otterscale-agent.fullname" . }}-config
            - secretRef:
                name: {{ include "otterscale-agent.fullname" . }}
