{{- if .Values.flux.enabled }}
{{ .Files.Get "files/rbac/flux-admin.yaml" }}
{{ .Files.Get "files/admission/flux-require-sa.yaml" }}
---
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    {{- toYaml .Values.flux.instance.distribution | nindent 4 }}
  components:
    {{- toYaml .Values.flux.instance.components | nindent 4 }}
  cluster:
    {{- toYaml .Values.flux.instance.cluster | nindent 4 }}
{{- end }}
