---
apiVersion: v1
kind: Secret
metadata:
  name: otterscale-harbor-robot
  namespace: otterscale-system
type: Opaque
stringData:
  HARBOR_URL: {{ .Values.harbor.url | quote }}
  HARBOR_ROBOT_NAME: {{ .Values.harbor.robot.name | quote }}
  HARBOR_ROBOT_SECRET: {{ .Values.harbor.robot.secret | quote }}
