{{- if not .Values.agent.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  join-token: {{ .Values.agent.joinToken | quote }}
{{- end }}
