apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  OTTERSCALE_AGENT_ENROLMENT_TOKEN: {{ .Values.agent.enrolmentToken | quote }}
