apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otterscale-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale-agent.labels" . | nindent 4 }}
