apiVersion: v2
name: envoy-gateway
description: A Helm chart for envoy-gateway
type: application
version: 1.0.0
# renovate: image=docker.io/envoyproxy/gateway-helm
appVersion: 1.8.4
annotations:
  otterscale.io/type: module
  module.otterscale.io/namespace: envoy-gateway-system
dependencies:
  - name: gateway-helm
    version: 1.8.4
    repository: oci://docker.io/envoyproxy
    condition: gateway-helm.enabled
  - name: ai-gateway-crds-helm
    version: 1.1.0
    repository: oci://docker.io/envoyproxy
    condition: ai-gateway-crds-helm.enabled
  - name: ai-gateway-helm
    version: 1.1.0
    repository: oci://docker.io/envoyproxy
    condition: ai-gateway-helm.enabled
