rook-ceph-cluster:
  enabled: true

  toolbox:
    enabled: true

  monitoring:
    enabled: true

  cephClusterSpec:
    mon:
      count: 1
    mgr:
      count: 1
    dashboard:
      enabled: false
    network:
      provider: host
    storage:
      useAllDevices: false
      devicePathFilter: "^/dev/disk/by-rook/.*"
    disruptionManagement:
      managePodBudgets: false

  cephBlockPools:
    - name: ceph-blockpool
      spec:
        failureDomain: osd
        replicated:
          size: 1
          requireSafeReplicaSize: false
      storageClass:
        enabled: true
        name: ceph-block
        isDefault: true
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        volumeBindingMode: "Immediate"
        parameters:
          imageFormat: "2"
          imageFeatures: layering
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-publish-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/controller-publish-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-modify-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/controller-modify-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-publish-secret-name: rook-csi-rbd-node
          csi.storage.k8s.io/node-publish-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/fstype: ext4

  cephFileSystems:
    - name: ceph-filesystem
      spec:
        metadataPool:
          failureDomain: osd
          replicated:
            size: 1
            requireSafeReplicaSize: false
        dataPools:
          - name: data0
            failureDomain: osd
            replicated:
              size: 1
              requireSafeReplicaSize: false
        metadataServer:
          activeCount: 1
          activeStandby: true
          resources:
            limits:
              memory: "2Gi"
            requests:
              cpu: "250m"
              memory: "2Gi"
      storageClass:
        enabled: true
        isDefault: false
        name: ceph-filesystem
        pool: data0
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        volumeBindingMode: "Immediate"
        parameters:
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-publish-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/controller-publish-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/fstype: ext4

  cephObjectStores:
    - name: ceph-objectstore
      spec:
        metadataPool:
          failureDomain: osd
          replicated:
            size: 1
            requireSafeReplicaSize: false
        dataPool:
          failureDomain: osd
          replicated:
            size: 1
            requireSafeReplicaSize: false
        preservePoolsOnDelete: true
        gateway:
          port: 80
          instances: 1
          resources:
            limits:
              memory: "2Gi"
            requests:
              cpu: "250m"
              memory: "1Gi"
      storageClass:
        enabled: true
        name: ceph-bucket
        reclaimPolicy: Delete
        volumeBindingMode: "Immediate"
        annotations: {}
        labels: {}
        parameters:
          region: us-east-1
