---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        {{- toYaml .Values.kubevirt.featureGates | nindent 8 }}
      disabledFeatureGates:
        - Template
    imagePullPolicy: IfNotPresent
    {{- with .Values.kubevirt.pciHostDevices }}
    permittedHostDevices:
      pciHostDevices:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
