gpu-operator:
  enabled: true

  platform:
    openshift: false

  nfd:
    enabled: false

  psa:
    enabled: false

  cdi:
    enabled: true
    nriPluginEnabled: false

  sandboxWorkloads:
    enabled: false

  driver:
    enabled: false

  toolkit:
    enabled: false

  devicePlugin:
    enabled: false

  dcgm:
    enabled: false

  dcgmExporter:
    enabled: true

  gfd:
    enabled: true

  migManager:
    enabled: false

  nodeStatusExporter:
    enabled: false

  gds:
    enabled: false

  gdrcopy:
    enabled: false

  vgpuManager:
    enabled: false

  vgpuDeviceManager:
    enabled: false

  vfioManager:
    enabled: false

  kataManager:
    enabled: false

  sandboxDevicePlugin:
    enabled: false

  kataSandboxDevicePlugin:
    enabled: false

  ccManager:
    enabled: false
