gpu-operator:
  enabled: true

  nfd:
    enabled: false

  cdi:
    enabled: false

  sandboxWorkloads:
    enabled: true

  driver:
    enabled: true
    usePrecompiled: true
    repository: ghcr.io
    image: otterscale/nvidia-driver
    version: "580.173.02"
    upgradePolicy:
      autoUpgrade: false

  toolkit:
    env:
      - name: CONTAINERD_CONFIG
        value: /var/lib/rancher/rke2/agent/etc/containerd/config.toml
      - name: CONTAINERD_SOCKET
        value: /run/k3s/containerd/containerd.sock
      - name: CONTAINERD_RUNTIME_CLASS
        value: nvidia
      - name: CONTAINERD_SET_AS_DEFAULT
        value: "true"
      - name: SELINUX_ENABLED
        value: "true"

  devicePlugin:
    enabled: false

  migManager:
    enabled: false

  nodeStatusExporter:
    enabled: true

  vgpuDeviceManager:
    enabled: false
