{{- if .Values.harbor.enabled -}}

{{- $secretName := include "otterscale.harbor.adminSecretName" . -}}
{{- $passwordKey := include "otterscale.harbor.adminSecretKey" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/component: harbor
    {{- include "otterscale.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $passwordKey }}: {{ include "otterscale.harbor.adminPassword" . | b64enc | quote }}
{{- end }}
