{{- if and .Values.harbor.enabled .Values.keycloak.enabled .Values.harborOIDC.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.harborOIDC.configSecretName | default "otterscale-harbor-oidc-config" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: harbor
type: Opaque
stringData:
  CONFIG_OVERWRITE_JSON: |
    {
      "auth_mode": "oidc_auth",
      "oidc_name": "Keycloak",
      "oidc_endpoint": "{{ include "otterscale.keycloak.realmURL" . }}",
      "oidc_client_id": "{{ .Values.keycloakRealm.clients.harbor.id }}",
      "oidc_client_secret": "{{ include "otterscale.keycloak.harborClientSecret" . }}",
      "oidc_scope": "{{ .Values.harborOIDC.scope }}",
      "oidc_auto_onboard": {{ .Values.harborOIDC.autoOnboard }},
      "oidc_groups_claim": "{{ .Values.harborOIDC.groupsClaim }}",
      "oidc_admin_group": "{{ .Values.harborOIDC.adminGroup }}",
      "oidc_verify_cert": false,
      "oidc_logout": false,
      "oidc_user_claim": "sub",
      "primary_auth_mode": true
    }
{{- end }}
