{{- if and .Values.httpRoute.enabled .Values.harbor.enabled (eq (include "otterscale.scheme" .) "https") }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "otterscale.fullname" . }}-harbor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "otterscale.gateway.name" . }}
    namespace: {{ include "otterscale.gateway.namespace" . }}
    sectionName: {{ .Values.httpRoute.gateway.sectionName }}
  hostnames:
  - {{ include "otterscale.harbor.host" . | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ""
      kind: Service
      name: {{ include "otterscale.harbor.serviceName" . }}
      port: {{ include "otterscale.harbor.servicePort" . }}
{{- end }}
