apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "otterscale.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
spec:
  parentRefs:
  - kind: ListenerSet
    name: {{ include "otterscale.listenerSet.name" . }}
    sectionName: {{ include "otterscale.listenerSet.sectionName" . }}
  hostnames:
  - {{ include "otterscale.host" . | quote }}
  rules:
  {{- if .Values.keycloak.enabled }}
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.keycloak.http.relativePath }}
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        set:
        - name: X-Forwarded-Proto
          value: "https"
    backendRefs:
    - name: {{ include "otterscale.keycloak.fullname" . }}-http
      port: {{ .Values.keycloak.service.httpPort }}
    timeouts:
      backendRequest: 0s
      request: 0s
  {{- end }}
  - matches:
    - path:
        type: PathPrefix
        value: /api/
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: {{ include "otterscale.server.fullname" $ }}
      port: {{ .Values.server.service.port }}
    timeouts:
      backendRequest: 0s
      request: 0s
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "otterscale.dashboard.fullname" $ }}
      port: 3000
    timeouts:
      backendRequest: 0s
      request: 0s
