{{- if .Values.keycloak.enabled -}}
{{- $dashboardSecretName := printf "%s-dashboard-client-secret" (include "otterscale.keycloak.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $dashboardSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  client-secret: {{ include "otterscale.keycloak.dashboardClientSecret" . | quote }}
{{- if .Values.harbor.enabled }}
{{- $harborSecretName := printf "%s-harbor-client-secret" (include "otterscale.keycloak.fullname" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $harborSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  client-secret: {{ include "otterscale.keycloak.harborClientSecret" . | quote }}
{{- end }}
{{- end }}
