{{- if .Values.keycloak.enabled -}}

{{- $secretName := printf "%s-admin" (include "otterscale.keycloak.fullname" .) -}}
{{- $passwordKey := "KC_BOOTSTRAP_ADMIN_PASSWORD" -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: keycloak
    {{- include "otterscale.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $passwordKey }}: {{ include "otterscale.keycloak.adminPassword" . | b64enc | quote }}
{{- end }}
