{{- if .Values.keycloak.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale.keycloak.fullname" . }}-realm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  otterscale-realm.json: |
    {{- tpl (.Files.Get "files/keycloak-realm.json") . | nindent 4 }}
{{- end }}
