apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.server.labels" . | nindent 4 }}
type: Opaque
data:
  join-secret: {{ include "otterscale.joinSecret" . | b64enc | quote }}
