apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otterscale.server.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  OTTERSCALE_SERVER_ADDRESS: "0.0.0.0:8299"
  OTTERSCALE_SERVER_TUNNEL_ADDRESS: "0.0.0.0:8300"
  OTTERSCALE_SERVER_EXTERNAL_TUNNEL_URL: {{ include "otterscale.tunnel.externalURL" . | quote }}
  OTTERSCALE_SERVER_ALLOWED_ORIGINS: {{ include "otterscale.externalURL" . | quote }}
  {{- if .Values.keycloak.enabled }}
  OTTERSCALE_SERVER_KEYCLOAK_REALM_URL: {{ include "otterscale.keycloak.realmURL" . | quote }}
  OTTERSCALE_SERVER_KEYCLOAK_CLIENT_ID: {{ .Values.keycloakRealm.clients.dashboard.id | quote }}
  {{- end }}
