apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otterscale.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.server.labels" . | nindent 4 }}
automountServiceAccountToken: true
