{{- if .Values.valkey.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale.valkey.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
type: Opaque
data:
  default: {{ include "otterscale.valkey.password" . | b64enc | quote }}
{{- end }}
