apiVersion: v2
name: rook-ceph-csi-drivers
description: A Helm chart for rook-ceph-csi-drivers
type: application
version: 1.0.0
# renovate: helm=ceph-csi-drivers registry=https://ceph.github.io/ceph-csi-operator
appVersion: "v1.0.4"
annotations:
  otterscale.io/type: infrastructure
  module.otterscale.io/namespace: "rook-ceph"
  module.otterscale.io/depends-on: "rook-ceph"
dependencies:
  - name: ceph-csi-drivers
    version: "1.0.4"
    repository: "https://ceph.github.io/ceph-csi-operator"
    condition: ceph-csi-drivers.enabled
