apiVersion: v2
name: kserve
description: A Helm chart for kserve
type: application
version: 1.0.0
appVersion: "v0.20.0"
annotations:
  otterscale.io/type: module
  module.otterscale.io/namespace: "kserve"
  module.otterscale.io/depends-on: "envoy-ai-gateway,leader-worker-set"
dependencies:
  - name: kserve-llmisvc-crd
    # renovate: helm=kserve-llmisvc-crd registry=oci://ghcr.io/kserve/charts
    version: "v0.20.0"
    repository: "oci://ghcr.io/kserve/charts"
    condition: kserve-llmisvc-crd.enabled
