apiVersion: v2
name: kserve-configs
description: A Helm chart for kserve-configs
type: application
version: 1.0.0
appVersion: 0.20.0
annotations:
  otterscale.io/type: module
  module.otterscale.io/namespace: kserve
  module.otterscale.io/depends-on: kserve-resources
dependencies:
  - name: kserve-runtime-configs
    version: v0.20.0
    repository: oci://ghcr.io/kserve/charts
    condition: kserve-runtime-configs.enabled
