apiVersion: v2
name: kserve-resources
description: A Helm chart for kserve-resources
type: application
version: 1.0.0
appVersion: 0.20.0
annotations:
  otterscale.io/type: module
  module.otterscale.io/namespace: kserve
  module.otterscale.io/depends-on: kserve
dependencies:
  - name: kserve-llmisvc-resources
    # renovate: helm=kserve-llmisvc-resources registry=oci://ghcr.io/kserve/charts
    version: v0.20.0
    repository: oci://ghcr.io/kserve/charts
    condition: kserve-llmisvc-resources.enabled
