apiVersion: v2
name: node-feature-discovery
description: A Helm chart for node-feature-discovery
type: application
version: 1.0.0
# renovate: helm=node-feature-discovery registry=oci://registry.k8s.io/nfd/charts
appVersion: "v0.19.0"
annotations:
  otterscale.io/type: module
  module.otterscale.io/namespace: "node-feature-discovery"
dependencies:
  - name: node-feature-discovery
    version: 0.19.0
    repository: oci://registry.k8s.io/nfd/charts
    condition: node-feature-discovery.enabled
