apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: 1.0.0
# renovate: helm=cert-manager registry=oci://quay.io/jetstack/charts
appVersion: "v1.21.1"
annotations:
  module.otterscale.io/namespace: "cert-manager"
dependencies:
  - name: cert-manager
    version: "v1.21.1"
    repository: "oci://quay.io/jetstack/charts"
    condition: cert-manager.enabled
